// TODO Implement this library.
library user_model;

import 'package:json_annotation/json_annotation.dart';
// The file 'user_model.g.dart' is generated by `json_serializable`.
// If you see the error "Target of URI hasn't been generated", it means this file is missing.
// To fix this, run `flutter pub run build_runner build` in your project's root directory.
part 'user_model.g.dart';

@JsonSerializable()
class User {
  final String uid;
  final String email;
  final String? displayName;
  final String? photoUrl;
  final String? phoneNumber;
  final String? address;
  final String? role; // e.g., 'customer', 'seller', 'admin'
  final DateTime? createdAt;
  final DateTime? lastSignInAt;

  User({
    required this.uid,
    required this.email,
    this.displayName,
    this.photoUrl,
    this.phoneNumber,
    this.address,
    this.role = 'customer',
    this.createdAt,
    this.lastSignInAt,
  });

  factory User.fromJson(Map<String, dynamic> json) => _$UserFromJson(json);

  Map<String, dynamic> toJson() => _$UserToJson(this);

  User copyWith({
    String? uid,
    String? email,
    String? displayName,
    String? photoUrl,
    String? phoneNumber,
    String? address,
    String? role,
    DateTime? createdAt,
    DateTime? lastSignInAt,
  }) {
    return User(
      uid: uid ?? this.uid,
      email: email ?? this.email,
      displayName: displayName ?? this.displayName,
      photoUrl: photoUrl ?? this.photoUrl,
      phoneNumber: phoneNumber ?? this.phoneNumber,
      address: address ?? this.address,
      role: role ?? this.role,
      createdAt: createdAt ?? this.createdAt,
      lastSignInAt: lastSignInAt ?? this.lastSignInAt,
    );
  }
}