name: Build Android APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: 1. Ambil Kode
      uses: actions/checkout@v4

    - name: 2. Siapkan Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: 3. Siapkan Java JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: 4. Install Dependensi & Build Web Assets
      run: |
        npm install
        npm run build

    - name: 5. Sinkronisasi Capacitor
      run: |
        npx cap sync android

    - name: 6. Bypass Lisensi Android
      run: |
        mkdir -p $ANDROID_HOME/licenses
        echo -e "\n244d2425421163a6e9c24d834a47e200e00d18e7\n8522d5d84741a114b045bcbc055c680f1116d641\n7c6d05e4fb1fa574c924a019a4d9626b20469034" > $ANDROID_HOME/licenses/android-sdk-license

    - name: 7. Konfigurasi SDK & Aktifkan AndroidX
      run: |
        cd android
        echo "sdk.dir=$ANDROID_HOME" > local.properties
        echo "android.useAndroidX=true" >> gradle.properties
        echo "android.enableJetifier=true" >> gradle.properties

    - name: 8. Kompilasi Menjadi APK
      run: |
        cd android
        chmod +x gradlew
        ./gradlew assembleDebug --no-daemon

    - name: 9. Keluarkan File APK Matang
      uses: actions/upload-artifact@v4
      with:
        name: Aplikasi-Hotspot-Debug
        path: android/app/build/outputs/apk/debug/app-debug.apk
